### ISSUE TITLE
JSONs containing "# noqa"?

### ISSUE THREAD

**Issue by dunkeki** [oasis-open/cti-stix-common-objects#48]
Not sure about other JSON parsers, but Jackson barfs on many bundles within the repository.  These have (typically key-value) lines with a trailing "# noqa".  At the risk of exposing my Python ignorance, Google reports this as a comment indicating "no quality assurance".  Amusing that inserting it into a JSON creates a flawed object as far as I can tell per the JSON standard.

I added filters in our server code to catch these (removing the comment before parsing), but was curious if the repo contents should be remediated - thanks!

**Comment by dunkeki** [comment]
check out objects/extension-definition/extension-definition--005e229c-fffc-42b0-a912-84671ab2829d for an example

**Comment by rpiazza** [comment]
@dunkeki 

Thanks for point this out.  It was probably copied directly from a python file, and the #noqa is to tell the python linter not to mark the line as "too long".  I will remove any that I find and push up corrections.  In the meantime, you can safely delete #noqa from any STIX JSON file.

**Comment by rpiazza** [comment]
fixed
