### ISSUE TITLE
only one last one - a marking-definition with N/A modified field

### ISSUE THREAD

**Issue by dunkeki** [oasis-open/cti-stix-common-objects#50]
objects/marking-definition/marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf.json

has modified field which per the standard (I think) is N/A.

Qem asked me a while back to put in strict object checking.  It's really caused me more headaches than almost any aspect of our server, sorry...

I don't import / reference the objects/vulnerability GH directory, so I can't speak to any of those objects.  Thanks for all your work on this repo's content...

**Comment by rpiazza** [comment]
Hi @dunkeki,

Looks good to me - what am I missing????

**Comment by dunkeki** [comment]
That marking definition contains a modified time stamp. The modified member is marked as not applicable in marking definitions per the standard.  For strict object compliance it needs to be removed, sorry…

**Comment by rpiazza** [comment]
Done
