### ISSUE TITLE
broken objects

### ISSUE THREAD

**Issue by dunkeki** [oasis-open/cti-stix-common-objects#52]
objects/extension-definition/extension-definition--8f0b8ed7-c7ad-4650-babe-c4c45cac4a0b.json has weird extra characters, a broken, field, or something...it's not a valid JSON

objects/marking-definition/marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf.json has a _modified_ field which is not applicable for marking definition objects

thanks

**Comment by rpiazza** [comment]
@dunkeki,

Thanks for pointed these errors out - I have fixed them
