### ISSUE TITLE
extension definition object(s?) point to old schema directory names

### ISSUE THREAD

**Issue by dunkeki** [oasis-open/cti-stix-common-objects#58]
I don't know the extent of this issue, but our server went to use

objects/extension-definition/extension-definition--3a65884d-005a-4290-8335-cb2d778a83ce.json

and couldn't find the schema.  It appears that subdirectories in extension-definition-specifications have been renamed (i.e. "extension-definition-specifications/acs-marking-definition-3a6"), but the extension definition object *schema* field still points to the previous name (i.e. acs-data-markings).

Certainly this object needs to be updated and I'm guessing there are many others (the ones that should point to the renamed schema directores)...thanks.

**Comment by rpiazza** [comment]
@dunkeki - yes we are doing some reorganization.  I need to send out an announcement to CTI TC mailing list, which I will be doing today.  Thanks for reminding us that we also need to change the extension-definition object!

**Comment by rpiazza** [comment]
This is fixed
