### ISSUE TITLE
$id values on schema need to be updated

### ISSUE THREAD

**Issue by dunkeki** [oasis-open/cti-stix-common-objects#62]
The schema $id values - which are used to set the URI context for $ref appearing within the schema - still reflect the old directory names, e.g.

extension-definition-specifications/acs-marking-definition-3a6/extension-definition--3a65884d-005a-4290-8335-cb2d778a83ce.json

has

  "$id": "https://raw.githubusercontent.com/oasis-open/cti-stix-common-objects/main/extension-definition-specifications/**acs-data-markings/**extension-definition--3a65884d-005a-4290-8335-cb2d778a83ce.json",

but should be

  "$id": "https://raw.githubusercontent.com/oasis-open/cti-stix-common-objects/main/extension-definition-specifications/**acs-marking-definition-ea6**/extension-definition--3a65884d-005a-4290-8335-cb2d778a83ce.json",

Sorry, but your renaming decision is creating a significant ripple effect, thanks.

**Comment by dunkeki** [comment]
(the markdown is wrong on the URIs, sorry, but I think you get the idea, thanks)

**Comment by rpiazza** [comment]
@dunkeki - another great catch.  So glad you are finding them.  Unfortunately, we don't currently have any testing for this repository.  It should be fixed now - reopen if not.
