### ISSUE TITLE
extra spaces in extension-definition

### ISSUE THREAD

**Issue by lisch** [oasis-open/cti-stix-common-objects#9]
In `extension-definition--3a65884d-005a-4290-8335-cb2d778a83ce.json`, the value of the `id` property contains a leading and trailing space character. As a result, stix2.FileSystemSource raises an exception, reporting an invalid `id`.

**Comment by rpiazza** [comment]
@lisch 

Thanks for catching that.  It is now fixed in the main branch

**Comment by lisch** [comment]
The leading space has been deleted, but the trailing space remains. As a result, stix2.FileSystemSource still raises an exception.

**Comment by rpiazza** [comment]
:-(. 

Fixed in main branch
